name: Build OTC Zimbadev 15.03 (Windows x64)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows (vcpkg manifest)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC (VS2022)
        uses: ilammy/msvc-dev-cmd@v1

      # 1) Criar o vcpkg.json na RAIZ do repo
      - name: Create vcpkg.js
